AllCops:
  TargetRubyVersion: 2.1

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Metrics/LineLength:
  Max: 90

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Style/ClassAndModuleChildren:
  Enabled: false

# I need to use singleton so gem stays simple
Style/ClassVars:
  Enabled: false
